In [5]:
### Assingment 1

import numpy as np


In [3]:
a = np.zeros(10,dtype='int32')

In [4]:
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [10]:
##Assginment 2


import numpy as np
a=np.random.randint(10,49,size=(10))
print(a)

[27 46 36 17 34 19 11 32 29 10]


In [12]:
## Assignment 3

import numpy as np
a=np.random.randint(0,8,size=(3,3))
print(a)

[[3 1 4]
 [2 3 3]
 [0 6 3]]


In [14]:
## Assignment 4


import numpy as np
a=np.array([1,2,0,0,4,0])
for i in range(6):
    if a[i]!=0:
        
        print(i)

0
1
4


In [18]:
##Assignment 5

import numpy as np
a=np.random.rand(10,10)
print(a)


[[0.2981802  0.94687907 0.28124087 0.3929879  0.45896659 0.90155763
  0.88675619 0.56659832 0.53545418 0.29508923]
 [0.82277578 0.40813089 0.77155037 0.59012047 0.47307779 0.15361082
  0.42874949 0.57347912 0.93379917 0.69876447]
 [0.94502818 0.91807134 0.65617527 0.00391355 0.85465089 0.00347963
  0.02952188 0.10248583 0.4530539  0.76114849]
 [0.7868757  0.98959404 0.38892504 0.28321061 0.92663174 0.44249777
  0.57609247 0.74643686 0.96923317 0.48486085]
 [0.41357136 0.85388098 0.38637524 0.2804754  0.13037539 0.58608033
  0.0742769  0.29329916 0.66547265 0.76667761]
 [0.31607232 0.26921319 0.10262138 0.01429983 0.68020251 0.40995731
  0.46551592 0.18411233 0.63810617 0.56211504]
 [0.00162918 0.78928487 0.99810057 0.08873319 0.0853023  0.43648723
  0.68556713 0.6891503  0.69299655 0.76320607]
 [0.08888324 0.98798676 0.89509918 0.13691633 0.03738296 0.86831382
  0.54871301 0.1355964  0.17114993 0.94682317]
 [0.82881391 0.7878014  0.30090907 0.60065702 0.18050992 0.43955527
  0.48848713

In [19]:
np.min(a)

0.001629180780809869

In [20]:
np.max(a)

0.9981005679204507

In [21]:
##Assignment 6


import numpy as np
a=np.random.randint(0,100,size=(30))
print(a)


[98 79 23 60 55 47  8 58 74 44 55 50 58 38 40 27 38 10 51 71 80 52  8 90
 14 73 14 48 75 49]


In [22]:
np.mean(a)

49.56666666666667